# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
            
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(700, 500)
        LoginWindow.setMinimumSize(QtCore.QSize(700, 500))
        LoginWindow.setMaximumSize(QtCore.QSize(700, 500))
        LoginWindow.setUnifiedTitleAndToolBarOnMac(False)
        
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.rightFrame = QtWidgets.QFrame(self.centralwidget)
        self.rightFrame.setGeometry(QtCore.QRect(300, 0, 400, 500))
        self.rightFrame.setStyleSheet("background-color: #ffffff;")
        self.rightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        
        self.minimumButton = QtWidgets.QPushButton(self.rightFrame)
        self.minimumButton.setGeometry(QtCore.QRect(330, 10, 20, 20))
        self.minimumButton.setStyleSheet("QPushButton {\n"
"    color: #ffffff;\n"
"    background-color: #020202;\n"
"    border: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5E616A;\n"
"}")
        self.minimumButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resource/Minimize_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.minimumButton.setIcon(icon1)
        self.minimumButton.setIconSize(QtCore.QSize(13, 13))
        self.minimumButton.setObjectName("minimumButton")
        
        self.exitButton = QtWidgets.QPushButton(self.rightFrame)
        self.exitButton.setGeometry(QtCore.QRect(360, 10, 20, 20))
        self.exitButton.setStyleSheet("QPushButton {\n"
"    color: #ffffff;\n"
"    background-color: #020202;\n"
"    border: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5E616A;\n"
"}")
        self.exitButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resource/Close_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.exitButton.setIcon(icon2)
        
        self.exitButton.setIconSize(QtCore.QSize(13, 13))
        self.exitButton.setObjectName("exitButton")
        
        self.label_id = QtWidgets.QLabel(self.rightFrame)
        self.label_id.setGeometry(QtCore.QRect(30, 207, 70, 25))
        self.label_id.setStyleSheet("color: #020202;\n"
"border: 0px;")
        self.label_id.setObjectName("label_id")
        
        self.idFrame = QtWidgets.QFrame(self.rightFrame)
        self.idFrame.setGeometry(QtCore.QRect(100, 200, 250, 40))
        self.idFrame.setStyleSheet("background-color:  #ffffff;\n"
"border: 1px solid  #020202;\n"
"border-bottom-left-radius:3px;\n"
"border-top-left-radius: 3;\n"
"border-bottom-right-radius: 3px;\n"
"border-top-right-radius: 3px;")
        self.idFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.idFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.idFrame.setObjectName("idFrame")
        self.idEdit = QtWidgets.QLineEdit(self.idFrame)
        self.idEdit.setGeometry(QtCore.QRect(10, 10, 230, 20))
        self.idEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.idEdit.setStyleSheet("background-color:  #ffffff;\n"
"color: #020202;\n"
"border: 0px;")
        self.idEdit.setObjectName("idEdit")
        
        self.label_pw = QtWidgets.QLabel(self.rightFrame)
        self.label_pw.setGeometry(QtCore.QRect(30, 257, 70, 25))
        self.label_pw.setStyleSheet("color: #020202;\n"
"border: 0px;")
        self.label_pw.setObjectName("label_pw")
        self.pwFrame = QtWidgets.QFrame(self.rightFrame)
        self.pwFrame.setGeometry(QtCore.QRect(100, 250, 250, 40))
        self.pwFrame.setStyleSheet("background-color:  #ffffff;\n"
"border: 1px solid  #020202;\n"
"border-bottom-left-radius:3px;\n"
"border-top-left-radius: 3;\n"
"border-bottom-right-radius: 3px;\n"
"border-top-right-radius: 3px;")
        self.pwFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pwFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pwFrame.setObjectName("pwFrame")
        self.pwEdit = QtWidgets.QLineEdit(self.pwFrame)
        self.pwEdit.setGeometry(QtCore.QRect(10, 10, 230, 20))
        self.pwEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.pwEdit.setStyleSheet("background-color:  #ffffff;\n"
"color: #020202;\n"
"border: 0px;")
        self.pwEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwEdit.setObjectName("pwEdit")
        self.idpw_checkbox = QtWidgets.QCheckBox(self.rightFrame)
        self.idpw_checkbox.setGeometry(QtCore.QRect(200, 290, 150, 25))
        self.idpw_checkbox.setStyleSheet("QCheckBox {\n"
"    color: #020202;\n"
"}\n"
"")
        self.idpw_checkbox.setObjectName("idpw_checkbox")
        
        self.loginButton = QtWidgets.QPushButton(self.rightFrame)
        self.loginButton.setGeometry(QtCore.QRect(120, 340, 200, 35))
        self.loginButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255,255,255);\n"
"    background-color:#020202;\n"
"    text-align: center;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: #5E616A;\n"
"}")
        self.loginButton.setIconSize(QtCore.QSize(16, 16))
        self.loginButton.setObjectName("loginButton")
       
        self.remoteButton = QtWidgets.QPushButton(self.rightFrame)
        self.remoteButton.setGeometry(QtCore.QRect(120, 385, 200, 35))
        self.remoteButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255,255,255);\n"
"    background-color:#020202;\n"
"    text-align: center;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: #5E616A;\n"
"}")
        self.remoteButton.setIconSize(QtCore.QSize(50, 50))
        self.remoteButton.setObjectName("remoteButton")
        
        
        self.leftFrame = QtWidgets.QFrame(self.centralwidget)
        self.leftFrame.setGeometry(QtCore.QRect(0, 0, 300, 500))
        self.leftFrame.setStyleSheet("background-color: #FFFFFF;")
        self.leftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftFrame.setObjectName("leftFrame")
        
        self.logoFrame = QtWidgets.QFrame(self.leftFrame)
        self.logoFrame.setGeometry(QtCore.QRect(50, 150, 200, 200))
        self.logoFrame.setStyleSheet("image: url(resource/main_logo.png);\n"
"background-color: rgba(255, 255, 255,0);\n"
"border: 0px;")
        self.logoFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoFrame.setObjectName("logoFrame")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Login"))
        self.idpw_checkbox.setText(_translate("LoginWindow", "ID/PW 저장"))
        self.loginButton.setText(_translate("LoginWindow", "로그인"))
        self.remoteButton.setText(_translate("LoginWindow", "원격지원"))
        self.label_id.setText(_translate("LoginWindow", "아이디"))
        self.label_pw.setText(_translate("LoginWindow", "비밀번호"))

