# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Process_Ui(object):
    def setupUi(self, window):
            
        window.setObjectName("LoginWindow")
        window.resize(700, 500)
        window.setMinimumSize(QtCore.QSize(500, 200))
        window.setMaximumSize(QtCore.QSize(500, 200))
        window.setUnifiedTitleAndToolBarOnMac(False)
        
        self.mainwidget = QtWidgets.QWidget(window)
        self.mainwidget.setObjectName("centralwidget")
        
        self.frame = QtWidgets.QFrame(self.mainwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 500, 200))
        self.frame.setStyleSheet("background-color: #ffffff;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("rightFrame")
        
        self.title = QtWidgets.QLabel(self.frame)
        self.title.setGeometry(QtCore.QRect(0, 50, 500, 30))
        self.title.setStyleSheet("color: #020202;\n"
"border: 0px;")
        self.title.setObjectName("title")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setText("프로그램을 실행중입니다... 잠시만 기다려주세요...")
        
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(20, 120, 460, 20))
        self.progressBar.setStyleSheet("QProgressBar\n"
"{\n"
"    border: solid grey;\n"
"    border-radius: 10px;\n"
"    background-color: #bfbfbf;\n"
"    color: black;\n"
"}\n"
"QProgressBar::chunk \n"
"{\n"
"    background-color: qlineargradient(spread:pad, x5:0, y1:0, x5:0, y2:0, stop:0 #020202, stop:1 #020202);\n"
"/*\n"
"    background-color: #ffffff;\n"
"*/\n"
"    border-radius :10px;\n"
"}   ")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
 
        window.setCentralWidget(self.mainwidget)
        QtCore.QMetaObject.connectSlotsByName(window)


